#!/bin/bash

gcc \
	`pkg-config gstreamer-1.0 --cflags` \
	`pkg-config glib-2.0 --cflags` \
	`pkg-config gstreamer-plugins-bad-1.0 --cflags` \
	`pkg-config gstreamer-1.0 --libs` \
	`pkg-config gstreamer-plugins-bad-1.0 --libs` \
	record.c -o record

gcc \
	`pkg-config gstreamer-1.0 --cflags` \
	`pkg-config glib-2.0 --cflags` \
	`pkg-config gstreamer-plugins-bad-1.0 --cflags` \
	`pkg-config gstreamer-rtsp-server-1.0 --cflags` \
	`pkg-config gstreamer-1.0 --libs` \
	`pkg-config gstreamer-plugins-bad-1.0 --libs` \
	`pkg-config gstreamer-rtsp-server-1.0 --libs` \
	server.c -o server
