#!/bin/bash

mkdir -p bin

gcc \
	`pkg-config gstreamer-1.0 --cflags` \
	`pkg-config glib-2.0 --cflags` \
	`pkg-config gstreamer-plugins-bad-1.0 --cflags` \
	`pkg-config gstreamer-1.0 --libs` \
	`pkg-config gstreamer-plugins-bad-1.0 --libs` \
	-Ishared \
	shared/gcs/dir.c shared/gcs/chunk.c shared/gcs/index.c shared/gcs/adder.c chunk-recorder/chunk-recorder.c -o bin/chunk-recorder

gcc \
	`pkg-config gstreamer-1.0 --cflags` \
	`pkg-config glib-2.0 --cflags` \
	`pkg-config gstreamer-plugins-bad-1.0 --cflags` \
	`pkg-config gstreamer-1.0 --libs` \
	`pkg-config gstreamer-plugins-bad-1.0 --libs` \
	-Ishared \
	shared/gcs/dir.c shared/gcs/chunk.c shared/gcs/index.c shared/gcs/adder.c chunk-player/chunk-player.c -o bin/chunk-player
